/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as SettingsConnectionsRouteImport } from './routes/settings.connections'
import { Route as SettingsKnowledgeRouteImport } from './routes/settings.knowledge'
import { Route as SettingsReportsRouteImport } from './routes/settings.reports'
import { Route as SettingsRulesAssistantRouteImport } from './routes/settings.rules-assistant'
import { Route as SettingsSourcesRouteImport } from './routes/settings.sources'
import { Route as ReportsTendersLabelRouteImport } from './routes/reports.tenders.$label'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsConnectionsRoute = SettingsConnectionsRouteImport.update({
  id: '/settings/connections',
  path: '/settings/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsKnowledgeRoute = SettingsKnowledgeRouteImport.update({
  id: '/settings/knowledge',
  path: '/settings/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsReportsRoute = SettingsReportsRouteImport.update({
  id: '/settings/reports',
  path: '/settings/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRulesAssistantRoute = SettingsRulesAssistantRouteImport.update({
  id: '/settings/rules-assistant',
  path: '/settings/rules-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSourcesRoute = SettingsSourcesRouteImport.update({
  id: '/settings/sources',
  path: '/settings/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsTendersLabelRoute = ReportsTendersLabelRouteImport.update({
  id: '/reports/tenders/$label',
  path: '/reports/tenders/$label',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/audit': typeof AuditRoute
  '/login': typeof LoginRoute
  '/memory': typeof MemoryRoute
  '/onboarding': typeof OnboardingRoute
  '/opportunities': typeof OpportunitiesRoute
  '/rules': typeof RulesRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/knowledge': typeof SettingsKnowledgeRoute
  '/settings/reports': typeof SettingsReportsRoute
  '/settings/rules-assistant': typeof SettingsRulesAssistantRoute
  '/settings/sources': typeof SettingsSourcesRoute
  '/reports/tenders/$label': typeof ReportsTendersLabelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/audit': typeof AuditRoute
  '/login': typeof LoginRoute
  '/memory': typeof MemoryRoute
  '/onboarding': typeof OnboardingRoute
  '/opportunities': typeof OpportunitiesRoute
  '/rules': typeof RulesRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/knowledge': typeof SettingsKnowledgeRoute
  '/settings/reports': typeof SettingsReportsRoute
  '/settings/rules-assistant': typeof SettingsRulesAssistantRoute
  '/settings/sources': typeof SettingsSourcesRoute
  '/reports/tenders/$label': typeof ReportsTendersLabelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/audit': typeof AuditRoute
  '/login': typeof LoginRoute
  '/memory': typeof MemoryRoute
  '/onboarding': typeof OnboardingRoute
  '/opportunities': typeof OpportunitiesRoute
  '/rules': typeof RulesRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/knowledge': typeof SettingsKnowledgeRoute
  '/settings/reports': typeof SettingsReportsRoute
  '/settings/rules-assistant': typeof SettingsRulesAssistantRoute
  '/settings/sources': typeof SettingsSourcesRoute
  '/reports/tenders/$label': typeof ReportsTendersLabelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/audit'
    | '/login'
    | '/memory'
    | '/onboarding'
    | '/opportunities'
    | '/rules'
    | '/settings/connections'
    | '/settings/knowledge'
    | '/settings/reports'
    | '/settings/rules-assistant'
    | '/settings/sources'
    | '/reports/tenders/$label'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/audit'
    | '/login'
    | '/memory'
    | '/onboarding'
    | '/opportunities'
    | '/rules'
    | '/settings/connections'
    | '/settings/knowledge'
    | '/settings/reports'
    | '/settings/rules-assistant'
    | '/settings/sources'
    | '/reports/tenders/$label'
  id:
    | '__root__'
    | '/'
    | '/approvals'
    | '/audit'
    | '/login'
    | '/memory'
    | '/onboarding'
    | '/opportunities'
    | '/rules'
    | '/settings/connections'
    | '/settings/knowledge'
    | '/settings/reports'
    | '/settings/rules-assistant'
    | '/settings/sources'
    | '/reports/tenders/$label'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AuditRoute: typeof AuditRoute
  LoginRoute: typeof LoginRoute
  MemoryRoute: typeof MemoryRoute
  OnboardingRoute: typeof OnboardingRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  RulesRoute: typeof RulesRoute
  SettingsConnectionsRoute: typeof SettingsConnectionsRoute
  SettingsKnowledgeRoute: typeof SettingsKnowledgeRoute
  SettingsReportsRoute: typeof SettingsReportsRoute
  SettingsRulesAssistantRoute: typeof SettingsRulesAssistantRoute
  SettingsSourcesRoute: typeof SettingsSourcesRoute
  ReportsTendersLabelRoute: typeof ReportsTendersLabelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/connections': {
      id: '/settings/connections'
      path: '/settings/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof SettingsConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/knowledge': {
      id: '/settings/knowledge'
      path: '/settings/knowledge'
      fullPath: '/settings/knowledge'
      preLoaderRoute: typeof SettingsKnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/reports': {
      id: '/settings/reports'
      path: '/settings/reports'
      fullPath: '/settings/reports'
      preLoaderRoute: typeof SettingsReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/rules-assistant': {
      id: '/settings/rules-assistant'
      path: '/settings/rules-assistant'
      fullPath: '/settings/rules-assistant'
      preLoaderRoute: typeof SettingsRulesAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/sources': {
      id: '/settings/sources'
      path: '/settings/sources'
      fullPath: '/settings/sources'
      preLoaderRoute: typeof SettingsSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/tenders/$label': {
      id: '/reports/tenders/$label'
      path: '/reports/tenders/$label'
      fullPath: '/reports/tenders/$label'
      preLoaderRoute: typeof ReportsTendersLabelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsRoute: ApprovalsRoute,
  AuditRoute: AuditRoute,
  LoginRoute: LoginRoute,
  MemoryRoute: MemoryRoute,
  OnboardingRoute: OnboardingRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  RulesRoute: RulesRoute,
  SettingsConnectionsRoute: SettingsConnectionsRoute,
  SettingsKnowledgeRoute: SettingsKnowledgeRoute,
  SettingsReportsRoute: SettingsReportsRoute,
  SettingsRulesAssistantRoute: SettingsRulesAssistantRoute,
  SettingsSourcesRoute: SettingsSourcesRoute,
  ReportsTendersLabelRoute: ReportsTendersLabelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
