"""Declarative base, shared column types, and naming conventions.

Constraint names are generated from a convention so that Alembic can always
name them deterministically — an unnamed constraint cannot be dropped in a
downgrade, and every migration here must be reversible.
"""

from __future__ import annotations

import uuid
from datetime import UTC, datetime
from typing import Any

from sqlalchemy import DateTime, MetaData, func
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)

    type_annotation_map = {
        dict[str, Any]: JSONB,
        list[str]: JSONB,
    }


def uuid_pk() -> Mapped[uuid.UUID]:
    """Primary key generated by the application.

    Client-side generation matters here: raw payloads are archived to Mongo
    under the id of the Postgres row they belong to, and the archive write
    frequently happens before the relational insert. We cannot wait for a
    database default to tell us the id.
    """
    return mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, sort_order=-100)


def utcnow() -> datetime:
    return datetime.now(UTC)


class TimestampMixin:
    """`created_at` / `updated_at`, both timezone-aware, both server-defaulted."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=utcnow, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=utcnow,
        server_default=func.now(),
        onupdate=utcnow,
    )


class CreatedAtMixin:
    """`created_at` only — for append-only tables that are never updated."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=utcnow, server_default=func.now()
    )
