"""custom tender sources

Adds the columns behind Settings → Sources & schedule → Add a site.

This migration was originally autogenerated before `alembic/env.py` grew its
`include_object` filter, so it also carried drops for `checkpoints`,
`checkpoint_blobs`, `checkpoint_writes` and `checkpoint_migrations`. Those
tables belong to LangGraph, which creates them itself at runtime — Alembic
never should have seen them, let alone dropped them.

That was wrong in two directions. On a database where the app had already run,
the drops succeeded and took the agent's checkpoint data with them. On a fresh
one — every deployment, and the migration check in CI — the index drop failed
outright and the whole upgrade stopped here.

The checkpoint operations are removed. Nothing else about this migration
changed, and a database that already applied the old version is left in exactly
the same shape: LangGraph recreates its tables on the next run.

Revision ID: caeb4249dcf4
Revises: 7e99061818b6
Create Date: 2026-08-23 18:05:10.993364
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "caeb4249dcf4"
down_revision: str | Sequence[str] | None = "7e99061818b6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column("tender_sources", sa.Column("listing_url", sa.String(length=500), nullable=True))
    # server_default so the NOT NULL holds for rows that already exist.
    op.add_column(
        "tender_sources",
        sa.Column(
            "fallback_urls", postgresql.ARRAY(sa.Text()), nullable=False, server_default="{}"
        ),
    )
    op.add_column(
        "tender_sources",
        sa.Column("is_custom", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column("tender_sources", sa.Column("entity", sa.String(length=300), nullable=True))


def downgrade() -> None:
    op.drop_column("tender_sources", "entity")
    op.drop_column("tender_sources", "is_custom")
    op.drop_column("tender_sources", "fallback_urls")
    op.drop_column("tender_sources", "listing_url")
